hashtags = {
    "instagram": [
        "instagram",
        "instagood",
        "like",
        "love",
        "follow",
        "photography",
        "photooftheday",
        "picoftheday",
        "art",
        "insta",
        "instalike",
        "fashion",
        "instadaily",
        "photo",
        "likeforlikes",
        "beautiful",
        "followme",
        "bhfyp",
        "life",
        "happy",
        "nature",
        "likes",
        "instapic",
        "style",
        "travel",
        "f",
        "music",
        "cute",
        "fun",
        "bhfyp",
    ]
}

